### ISSUE TITLE
suggest safer alternative

### ISSUE THREAD

**Issue by capaj** [lirantal/no-secrets-env-vars-website#1]
website lacks suggestion of what to use instead of env vars.
Also keep in mind a usecase where the code of the app is open sourced, so secrets cannot be just hardcoded in the codebase

**Comment by lirantal** [comment]
I've recorded some thoughts here: https://x.com/liran_tal/status/1842200587724570680

I'll turn those into a more formal write-up later
Thanks for opening the issue so I can get back to this!

**Comment by lirantal** [comment]
Comprehensive blog post write-up now here: [Do not use secrets in environment variables and here's how to do it better
](https://www.nodejs-security.com/blog/do-not-use-secrets-in-environment-variables-and-here-is-how-to-do-it-better)
